# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shapeviewer_gui_3.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(751, 511)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(740, 0))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.titleGroupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleGroupBox.sizePolicy().hasHeightForWidth())
        self.titleGroupBox.setSizePolicy(sizePolicy)
        self.titleGroupBox.setMinimumSize(QtCore.QSize(360, 140))
        self.titleGroupBox.setMaximumSize(QtCore.QSize(16777215, 140))
        self.titleGroupBox.setTitle(_fromUtf8(""))
        self.titleGroupBox.setObjectName(_fromUtf8("titleGroupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.titleGroupBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.titleLabel = QtGui.QLabel(self.titleGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setMinimumSize(QtCore.QSize(360, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.titleLabel.setTextFormat(QtCore.Qt.AutoText)
        self.titleLabel.setIndent(6)
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.verticalLayout_5.addWidget(self.titleLabel)
        self.horizontalLayout.addWidget(self.titleGroupBox)
        self.buttonGroupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonGroupBox.sizePolicy().hasHeightForWidth())
        self.buttonGroupBox.setSizePolicy(sizePolicy)
        self.buttonGroupBox.setMinimumSize(QtCore.QSize(360, 140))
        self.buttonGroupBox.setMaximumSize(QtCore.QSize(360, 140))
        self.buttonGroupBox.setBaseSize(QtCore.QSize(360, 0))
        self.buttonGroupBox.setTitle(_fromUtf8(""))
        self.buttonGroupBox.setObjectName(_fromUtf8("buttonGroupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.buttonGroupBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.mBtnZoomIn = QtGui.QPushButton(self.buttonGroupBox)
        self.mBtnZoomIn.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./images/zoomIn.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mBtnZoomIn.setIcon(icon)
        self.mBtnZoomIn.setIconSize(QtCore.QSize(50, 50))
        self.mBtnZoomIn.setObjectName(_fromUtf8("mBtnZoomIn"))
        self.horizontalLayout_3.addWidget(self.mBtnZoomIn)
        self.mBtnZoomOut = QtGui.QPushButton(self.buttonGroupBox)
        self.mBtnZoomOut.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./images/zomOut.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mBtnZoomOut.setIcon(icon1)
        self.mBtnZoomOut.setIconSize(QtCore.QSize(50, 50))
        self.mBtnZoomOut.setObjectName(_fromUtf8("mBtnZoomOut"))
        self.horizontalLayout_3.addWidget(self.mBtnZoomOut)
        self.mBtnAddRaster = QtGui.QPushButton(self.buttonGroupBox)
        self.mBtnAddRaster.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./images/addRaster.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mBtnAddRaster.setIcon(icon2)
        self.mBtnAddRaster.setIconSize(QtCore.QSize(50, 50))
        self.mBtnAddRaster.setObjectName(_fromUtf8("mBtnAddRaster"))
        self.horizontalLayout_3.addWidget(self.mBtnAddRaster)
        self.mBtnAddVector = QtGui.QPushButton(self.buttonGroupBox)
        self.mBtnAddVector.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("./images/addLayer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mBtnAddVector.setIcon(icon3)
        self.mBtnAddVector.setIconSize(QtCore.QSize(50, 50))
        self.mBtnAddVector.setObjectName(_fromUtf8("mBtnAddVector"))
        self.horizontalLayout_3.addWidget(self.mBtnAddVector)
        self.mBtnSelection = QtGui.QPushButton(self.buttonGroupBox)
        self.mBtnSelection.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("./images/select.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mBtnSelection.setIcon(icon4)
        self.mBtnSelection.setIconSize(QtCore.QSize(50, 50))
        self.mBtnSelection.setObjectName(_fromUtf8("mBtnSelection"))
        self.horizontalLayout_3.addWidget(self.mBtnSelection)
        self.horizontalLayout.addWidget(self.buttonGroupBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.canvasGroupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvasGroupBox.sizePolicy().hasHeightForWidth())
        self.canvasGroupBox.setSizePolicy(sizePolicy)
        self.canvasGroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.canvasGroupBox.setTitle(_fromUtf8(""))
        self.canvasGroupBox.setObjectName(_fromUtf8("canvasGroupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.canvasGroupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.canvasFrame = QtGui.QFrame(self.canvasGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvasFrame.sizePolicy().hasHeightForWidth())
        self.canvasFrame.setSizePolicy(sizePolicy)
        self.canvasFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.canvasFrame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.canvasFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.canvasFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.canvasFrame.setObjectName(_fromUtf8("canvasFrame"))
        self.verticalLayout_4.addWidget(self.canvasFrame)
        self.horizontalLayout_2.addWidget(self.canvasGroupBox)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.dropDownGroupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dropDownGroupBox.sizePolicy().hasHeightForWidth())
        self.dropDownGroupBox.setSizePolicy(sizePolicy)
        self.dropDownGroupBox.setMinimumSize(QtCore.QSize(270, 60))
        self.dropDownGroupBox.setMaximumSize(QtCore.QSize(270, 16777215))
        self.dropDownGroupBox.setBaseSize(QtCore.QSize(270, 0))
        self.dropDownGroupBox.setObjectName(_fromUtf8("dropDownGroupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dropDownGroupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.mFieldComboBox = QgsFieldComboBox(self.dropDownGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mFieldComboBox.sizePolicy().hasHeightForWidth())
        self.mFieldComboBox.setSizePolicy(sizePolicy)
        self.mFieldComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mFieldComboBox.setMaxVisibleItems(25)
        self.mFieldComboBox.setObjectName(_fromUtf8("mFieldComboBox"))
        self.verticalLayout_6.addWidget(self.mFieldComboBox)
        self.modeComboBox = QtGui.QComboBox(self.dropDownGroupBox)
        self.modeComboBox.setObjectName(_fromUtf8("modeComboBox"))
        self.verticalLayout_6.addWidget(self.modeComboBox)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.legendQDockWidget = QgsDockWidget(self.dropDownGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legendQDockWidget.sizePolicy().hasHeightForWidth())
        self.legendQDockWidget.setSizePolicy(sizePolicy)
        self.legendQDockWidget.setMinimumSize(QtCore.QSize(250, 22))
        self.legendQDockWidget.setMaximumSize(QtCore.QSize(250, 524287))
        self.legendQDockWidget.setBaseSize(QtCore.QSize(250, 0))
        self.legendQDockWidget.setObjectName(_fromUtf8("legendQDockWidget"))
        self.verticalLayout_8.addWidget(self.legendQDockWidget)
        self.verticalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_2.addWidget(self.dropDownGroupBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 751, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuMap_View = QtGui.QMenu(self.menubar)
        self.menuMap_View.setObjectName(_fromUtf8("menuMap_View"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMap_View.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Gis Viewer Application", None))
        self.titleLabel.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Black\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#0055ff;\">Land Development Model</span></p></body></html>", None))
        self.dropDownGroupBox.setTitle(_translate("MainWindow", "Model Results", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuMap_View.setTitle(_translate("MainWindow", "Map View", None))

from qgis.gui import *
#import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

