REM Change OSGEO4W_ROOT to point to the base install folder
SET OSGEO4W_ROOT=%~dp0QGIS
SET QGISNAME=qgis
SET QGIS=%OSGEO4W_ROOT%\apps\%QGISNAME%
SET QGIS_PREFIX_PATH=%QGIS%
SET GDAL_DATA=%OSGEO4W_ROOT%\share\gdal

REM Python Setup
SET PATH=%QGIS%\bin;%OSGEO4W_ROOT%\bin;%PATH%
SET PYTHONHOME=%OSGEO4W_ROOT%\apps\Python27
SET PYTHONPATH=%QGIS%\python;%PYTHONPATH%

python testGUI.py